export const list = [
	{
		name: 'Kerala banana',
		alsoKnownAs: ['Nendran banana', 'plantain banana'],
		kannadaName: 'ನೇಂದ್ರನ ಬಾಳೆ',
		kannadaTransliteration: 'Nēndrana bāḷe',
		hindiName: 'नेंद्रन केला',
		hindiTransliteration: 'nendran kela',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 3,
		averagePieces: null,
		averageKilos: 3,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: 60,
		image: 'images/alistair-smailes-tiisnvgaqCc-unsplash.jpg',
	},
	{
		name: 'banana',
		alsoKnownAs: [],
		kannadaName: 'ಬಾಳೆಹಣ್ಣು',
		kannadaTransliteration: 'Bāḷehaṇṇu',
		hindiName: 'केला',
		hindiTransliteration: 'kela',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 3,
		averagePieces: null,
		averageKilos: 3,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: 30,
		image: 'images/rodrigo-dos-reis-DkTuGvgPotA-unsplash.jpg',
	},
	{
		name: 'corn',
		alsoKnownAs: ['maize'],
		kannadaName: 'ಜೋಳ',
		kannadaTransliteration: 'Jōḷa',
		hindiName: 'भुट्टा',
		hindiTransliteration: 'bhutta',
		type: 'fruit',
		defaultPieces: 6,
		defaultKilos: null,
		averagePieces: 6,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: 10,
		costPerKilo: null,
		image: 'images/wouter-supardi-salari-HE_MjmWh9eQ-unsplash.jpg',
	},
	{
		name: 'apple',
		alsoKnownAs: [],
		kannadaName: 'ಸೇಬು',
		kannadaTransliteration: 'Sēbu',
		hindiName: 'सेब',
		hindiTransliteration: 'seb',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/matheus-cenali-wXuzS9xR49M-unsplash.jpg',
	},
	{
		name: 'green grape',
		alsoKnownAs: [],
		kannadaName: 'ಹಸಿರು ದ್ರಾಕ್ಷಿಗಳು',
		kannadaTransliteration: 'Hasiru drākṣigaḷu',
		hindiName: 'हरे अंगूर',
		hindiTransliteration: 'hare angoor',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/vitor-paladini-UqgTtfaikio-unsplash.jpg',
	},
	{
		name: 'purple grape',
		alsoKnownAs: [],
		kannadaName: 'ನೇರಳೆ ದ್ರಾಕ್ಷಿಗಳು',
		kannadaTransliteration: 'Nēraḷe drākṣigaḷu',
		hindiName: 'बैंगनी अंगूर',
		hindiTransliteration: 'bainganee angoor',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/nacho-dominguez-argenta-F_ilCik66Hg-unsplash.jpg',
	},
	{
		name: 'orange',
		alsoKnownAs: [],
		kannadaName: 'ಕಿತ್ತಳೆ',
		kannadaTransliteration: 'Kittaḷe',
		hindiName: 'नारंगी',
		hindiTransliteration: 'naarangee',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/jen-gunter-A4BBdJQu2co-unsplash.jpg',
	},
	{
		name: 'tomato',
		alsoKnownAs: [],
		kannadaName: 'ಟೊಮೆಟೊ',
		kannadaTransliteration: 'Ṭomeṭo',
		hindiName: 'टमाटर',
		hindiTransliteration: 'tamaatar',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: 2,
		averagePieces: null,
		averageKilos: 2,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: 25,
		image: 'images/engin-akyurt-eb26eV-ys_k-unsplash.jpg',
	},
	{
		name: 'catfish',
		alsoKnownAs: [],
		kannadaName: 'ಬೆಕ್ಕುಮೀನು',
		kannadaTransliteration: 'Bekkumīnu',
		hindiName: 'कैटफ़िश',
		hindiTransliteration: 'kaitafish',
		type: 'meat',
		defaultPieces: 3,
		defaultKilos: null,
		averagePieces: 3,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/istockphoto-513626238-612x612.jpg',
	},
	{
		name: 'shrimp',
		alsoKnownAs: [],
		kannadaName: 'ಸೀಗಡಿ',
		kannadaTransliteration: 'Sīgaḍi',
		hindiName: 'झींगा',
		hindiTransliteration: 'jheenga',
		type: 'meat',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/etienne-girardet-WTPMcV1NZuY-unsplash.jpg',
	},
	{
		name: 'crab',
		alsoKnownAs: [],
		kannadaName: 'ಏಡಿ',
		kannadaTransliteration: 'Ēḍi',
		hindiName: 'केकड़ा',
		hindiTransliteration: 'kekada',
		type: 'meat',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/jules-thomas-vM1Lz1ftMU8-unsplash.jpg',
	},
	{
		name: 'potato',
		alsoKnownAs: [],
		kannadaName: 'ಆಲೂಗಡ್ಡೆ',
		kannadaTransliteration: 'Ālūgaḍḍe',
		hindiName: 'आलू',
		hindiTransliteration: 'aaloo',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 5,
		averagePieces: null,
		averageKilos: 5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: 20,
		image: 'images/rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg',
	},
	{
		name: 'onion',
		alsoKnownAs: [],
		kannadaName: 'ಈರುಳ್ಳಿ',
		kannadaTransliteration: 'Īruḷḷi',
		hindiName: 'प्याज',
		hindiTransliteration: 'pyaaz',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 5,
		averagePieces: null,
		averageKilos: 5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/abhishek-hajare-D9h2-RxM1rE-unsplash.jpg',
	},
	{
		name: 'shallot',
		alsoKnownAs: ['sambar onion', 'small onion', 'pearl onion'],
		kannadaName: 'ಸಣ್ಣ ಈರುಳ್ಳಿ',
		kannadaTransliteration: 'Saṇṇa īruḷḷi',
		hindiName: 'छोटा प्याज',
		hindiTransliteration: 'chhota pyaaz',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 1,
		averagePieces: null,
		averageKilos: 1,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/dhivyaa-naraayani-TrpbyLfOG14-unsplash.jpg',
	},
	{
		name: 'bitter gourd',
		alsoKnownAs: ['bitter melon'],
		kannadaName: 'ಹಾಗಲಕಾಯಿ',
		kannadaTransliteration: 'Hāgalakāyi',
		hindiName: 'करेला',
		hindiTransliteration: 'karela',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/bitter-gourd-6534410_1280.jpg',
	},
	{
		name: 'kovaykka',
		alsoKnownAs: ['ivy gourd', 'scarlet gourd', 'dhendura', 'kudri'],
		kannadaName: 'ಐವಿ ಸೋರೆಕಾಯಿ',
		kannadaTransliteration: 'Aivi sōrekāyi',
		hindiName: 'आइवी लौकी',
		hindiTransliteration: 'aaivee laukee',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/1000_F_365521927_7C7ObBa61F2qbpzxKemBbgByRkSSUSWR.jpg',
	},
	{
		name: 'coconut',
		alsoKnownAs: [],
		kannadaName: 'ತೆಂಗಿನ ಕಾಯಿ',
		kannadaTransliteration: 'Teṅgina kāyi',
		hindiName: 'नारियल',
		hindiTransliteration: 'naariyal',
		type: 'fruit',
		defaultPieces: 5,
		defaultKilos: null,
		averagePieces: 5,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: 20,
		costPerKilo: undefined,
		image: 'images/louis-hansel-WUMxEBWvE64-unsplash.jpg',
	},
	{
		name: 'garlic',
		alsoKnownAs: [],
		kannadaName: 'ಬೆಳ್ಳುಳ್ಳಿ',
		kannadaTransliteration: 'Beḷḷuḷḷi',
		hindiName: 'लहसुन',
		hindiTransliteration: 'lahasun',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.25,
		averagePieces: null,
		averageKilos: 0.25,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/team-voyas-vIiye0QDryo-unsplash.jpg',
	},
	{
		name: 'beans',
		alsoKnownAs: [],
		kannadaName: 'ಬೀನ್ಸ್',
		kannadaTransliteration: 'Bīns',
		hindiName: 'फलियाँ',
		hindiTransliteration: 'phaliyaan',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/matilda-bellman-bEnSMaiHeX0-unsplash.jpg',
	},
	{
		name: 'okra',
		alsoKnownAs: ["lady's fingers"],
		kannadaName: 'ಬೆಂಡೆಕಾಯಿ',
		kannadaTransliteration: 'Beṇḍekāyi',
		hindiName: 'ओकरा',
		hindiTransliteration: 'okara',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/mirko-sajkov-lVIbdPYbHKw-unsplash.jpg',
	},
	{
		name: 'green eggplant',
		alsoKnownAs: ['green aubergine', 'green brinjal', 'green baigan'],
		kannadaName: 'ಹಸಿರು ಬಿಳಿಬದನೆ',
		kannadaTransliteration: 'Hasiru biḷibadane',
		hindiName: 'हरा बैंगन',
		hindiTransliteration: 'hara baingan',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/thai-long-green-eggplant-seeds.jpg',
	},
	{
		name: 'purple eggplant',
		alsoKnownAs: ['purple aubergine', 'purple brinjal', 'purple baigan'],
		kannadaName: 'ನೇರಳೆ ಬಿಳಿಬದನೆ',
		kannadaTransliteration: 'Nēraḷe biḷibadane',
		hindiName: 'बैंगनी बैंगन',
		hindiTransliteration: 'bainganee baingan',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/dillon-lobo-HBOxYKIAIYM-unsplash.jpg',
	},
	{
		name: 'cabbage',
		alsoKnownAs: [],
		kannadaName: 'ಎಲೆಕೋಸು',
		kannadaTransliteration: 'Elekōsu',
		hindiName: 'पत्ता गोभी',
		hindiTransliteration: 'patta gobhee',
		type: 'leaf vegetable',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/natasha-skov-ujh4hU9S-KA-unsplash.jpg',
	},
	{
		name: 'cabbage',
		alsoKnownAs: [],
		kannadaName: 'ಹೂಕೋಸು',
		kannadaTransliteration: 'Hūkōsu',
		hindiName: 'फूलगोभी',
		hindiTransliteration: 'phoolagobhee',
		type: 'vegetable',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/irene-kredenets-zNsSGYXaeP8-unsplash.jpg',
	},
	{
		name: 'carrot',
		alsoKnownAs: [],
		kannadaName: 'ಕ್ಯಾರೆಟ್',
		kannadaTransliteration: 'Kyāreṭ',
		hindiName: 'गाजर',
		hindiTransliteration: 'gaajar',
		type: 'vegetable',
		defaultPieces: 5,
		defaultKilos: null,
		averagePieces: 5,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: undefined,
		costPerKilo: null,
		image: 'images/rodrigo-dos-reis-ZgDHMMd72I8-unsplash.jpg',
	},
	{
		name: 'beetroot',
		alsoKnownAs: [],
		kannadaName: 'ಬೀಟ್ರೂಟ್',
		kannadaTransliteration: 'Bīṭrūṭ',
		hindiName: 'चुकंदर',
		hindiTransliteration: 'chukandar',
		type: 'vegetable',
		defaultPieces: 6,
		defaultKilos: null,
		averagePieces: 6,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/emma-jane-hobden-lFxgx7Snyfw-unsplash.jpg',
	},
	{
		name: 'green chilli',
		alsoKnownAs: ['chilli', 'chilly'],
		kannadaName: 'ಹಸಿರು ಮೆಣಸಿನಕಾಯಿ',
		kannadaTransliteration: 'Hasiru meṇasinakāyi',
		hindiName: 'हरी मिर्च',
		hindiTransliteration: 'haree mirch',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.5,
		averagePieces: null,
		averageKilos: 0.5,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/vipul-borade-FvvgvCO-0gI-unsplash.jpg',
	},
	{
		name: 'ginger',
		alsoKnownAs: [],
		kannadaName: 'ಶುಂಠಿ',
		kannadaTransliteration: 'Śuṇṭhi',
		hindiName: 'अदरक',
		hindiTransliteration: 'adarak',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: 0.25,
		averagePieces: null,
		averageKilos: 0.25,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/dean-david--vN_tvbzWJw-unsplash.jpg',
	},
	{
		name: 'cucumber',
		alsoKnownAs: [],
		kannadaName: 'ಸೌತೆಕಾಯಿ',
		kannadaTransliteration: 'Sautekāyi',
		hindiName: 'खीरा',
		hindiTransliteration: 'kheera',
		type: 'vegetable',
		defaultPieces: null,
		defaultKilos: undefined,
		averagePieces: null,
		averageKilos: undefined,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/mohamed-hassouna-hCJZwPFlk4E-unsplash.jpg',
	},
	{
		name: 'pineapple',
		alsoKnownAs: [],
		kannadaName: 'ಅನಾನಸ್',
		kannadaTransliteration: 'Anānas',
		hindiName: 'अनानास',
		hindiTransliteration: 'anaanaas',
		type: 'fruit',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: null,
		image: 'images/phoenix-han-ZS_RypKo9sk-unsplash.jpg',
	},
	{
		name: 'watermelon',
		alsoKnownAs: [],
		kannadaName: 'ಕಲ್ಲಂಗಡಿ',
		kannadaTransliteration: 'Kallaṅgaḍi',
		hindiName: 'तरबूज',
		hindiTransliteration: 'tarabooj',
		type: 'fruit',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: null,
		image: 'images/j-d-hUkZv0Y47Ic-unsplash.jpg',
	},
	{
		name: 'lemon',
		alsoKnownAs: [],
		kannadaName: 'ನಿಂಬೆ',
		kannadaTransliteration: 'Nimbe',
		hindiName: 'नींबू',
		hindiTransliteration: 'neemboo',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: undefined,
		averagePieces: null,
		averageKilos: undefined,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/thitiphum-koonjantuek-TFqjlTmkeyY-unsplash.jpg',
	},
	{
		name: 'lime',
		alsoKnownAs: [],
		kannadaName: 'ನಿಂಬೆ',
		kannadaTransliteration: 'Nimbe',
		hindiName: 'नींबू',
		hindiTransliteration: 'neemboo',
		type: 'fruit',
		defaultPieces: null,
		defaultKilos: undefined,
		averagePieces: null,
		averageKilos: undefined,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: null,
		costPerKilo: undefined,
		image: 'images/victor-figueroa-huUI0y0ERMM-unsplash.jpg',
	},
	{
		name: 'coriander',
		alsoKnownAs: [],
		kannadaName: 'ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು',
		kannadaTransliteration: 'Kottambari soppu',
		hindiName: 'धनिया',
		hindiTransliteration: 'dhaniya',
		type: 'leaf vegatable',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: undefined,
		costPerKilo: null,
		image: 'images/chandan-chaurasia-N73L0EzbJ8Y-unsplash.jpg',
	},
	{
		name: 'parsley',
		alsoKnownAs: [],
		kannadaName: 'ಪಾರ್ಸ್ಲಿ',
		kannadaTransliteration: 'Pārsli',
		hindiName: 'अजमोद',
		hindiTransliteration: 'ajamod',
		type: 'leaf vegatable',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: undefined,
		costPerKilo: null,
		image: 'images/hanna-stolt-Ea8il0_J4-A-unsplash.jpg',
	},
	{
		name: 'mint',
		alsoKnownAs: [],
		kannadaName: 'ಪುದೀನ',
		kannadaTransliteration: 'Pudīna',
		hindiName: 'पुदीना',
		hindiTransliteration: 'pudeena',
		type: 'leaf vegatable',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: undefined,
		costPerKilo: null,
		image: 'images/simon-lee-bHWRSq8fUUE-unsplash.jpg',
	},
	{
		name: 'tulsi',
		alsoKnownAs: ['holy basil', 'basil'],
		kannadaName: 'ತುಳಸಿ',
		kannadaTransliteration: 'Tuḷasi',
		hindiName: 'तुलसी',
		hindiTransliteration: 'tulasee',
		type: 'leaf vegatable',
		defaultPieces: 1,
		defaultKilos: null,
		averagePieces: 1,
		averageKilos: null,
		dateBoughtLast: [],
		quantityBought: [],
		costPerPiece: undefined,
		costPerKilo: null,
		image: 'images/rob-pumphrey-_f26vO7Cg_g-unsplash.jpg',
	},
];
